package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"
	"go-graphql/graph/model"

	"golang.org/x/crypto/bcrypt"
)

func (r *mutationResolver) CreateUser(ctx context.Context, input *model.NewUserInput) (*model.User, error) {
	user := &model.User{
		ID:       fmt.Sprintf("T%d", len(r.Resolver.Users)+1),
		Name:     input.Name,
		Email:    input.Email,
		Password: hashPassword(input.Password),
		Activate: input.Activate,
	}
	r.Resolver.Users = append(r.Resolver.Users, user)
	return user, nil
}
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string, email string) (*model.User, error) {
	for _, user := range r.Resolver.Users {
		if user.ID == id {
			user.Name = name
			user.Email = email
			return user, nil
		}
	}
	return nil, fmt.Errorf("user %s not found", id)
}
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	for i, user := range r.Resolver.Users {
		if user.ID == id {
			r.Resolver.Users = append(r.Resolver.Users[:i], r.Resolver.Users[i+1:]...)
			return user, nil
		}
	}
	return nil, fmt.Errorf("user %s not found", id)
}

// All is the resolver for the all field.
func (r *queryResolver) All(ctx context.Context) ([]*model.User, error) {
	return r.Resolver.Users, nil
}

// Find is the resolver for the find field.
func (r *queryResolver) Find(ctx context.Context, id string) (*model.User, error) {
	for _, user := range r.Resolver.Users {
		if user.ID == id {
			return user, nil
		}
	}
	return nil, fmt.Errorf("user %s not found", id)
}

// FindByEmail is the resolver for the findByEmail field.
func (r *queryResolver) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	for _, user := range r.Resolver.Users {
		if user.Email == email {
			return user, nil
		}
	}
	return nil, fmt.Errorf("user with email %s not found", email)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func hashPassword(password string) string {
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		panic("Error al hashear la contraseña")
	}
	return string(hashedPassword)
}
